-- MySQL Script generated by MySQL Workbench
-- Wed Oct  4 13:20:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Slackbot_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Slackbot_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Slackbot_DB` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `Slackbot_DB` ;

-- -----------------------------------------------------
-- Table `Slackbot_DB`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Slackbot_DB`.`questions` ;

CREATE TABLE IF NOT EXISTS `Slackbot_DB`.`questions` (
  `question_id` INT NOT NULL,
  `question` TINYTEXT NOT NULL,
  PRIMARY KEY (`question_id`),
  UNIQUE INDEX `Question_ID_UNIQUE` (`question_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Slackbot_DB`.`raters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Slackbot_DB`.`raters` ;

CREATE TABLE IF NOT EXISTS `Slackbot_DB`.`raters` (
  `rater_id` INT NOT NULL,
  `rater` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rater_id`),
  UNIQUE INDEX `Rater_ID_UNIQUE` (`rater_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Slackbot_DB`.`ask_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Slackbot_DB`.`ask_table` ;

CREATE TABLE IF NOT EXISTS `Slackbot_DB`.`ask_table` (
  `job_id` INT NOT NULL AUTO_INCREMENT,
  `target` VARCHAR(40) NOT NULL,
  `question_id` INT NOT NULL,
  `rater_id` INT NOT NULL,
  `response` CHAR(1) NULL DEFAULT NULL,
  INDEX `question_id_idx` (`question_id` ASC),
  INDEX `rater_id_idx` (`rater_id` ASC),
  PRIMARY KEY (`job_id`),
  UNIQUE INDEX `job_id_UNIQUE` (`job_id` ASC),
  CONSTRAINT `question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `Slackbot_DB`.`questions` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rater_id`
    FOREIGN KEY (`rater_id`)
    REFERENCES `Slackbot_DB`.`raters` (`rater_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO slack_user;
 DROP USER slack_user;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'slack_user' IDENTIFIED BY 'rhabit123';

GRANT ALL ON `Slackbot_DB`.* TO 'slack_user';
GRANT ALL ON `new_schema1`.* TO 'slack_user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Slackbot_DB`.`questions`
-- -----------------------------------------------------
START TRANSACTION;
USE `Slackbot_DB`;
INSERT INTO `Slackbot_DB`.`questions` (`question_id`, `question`) VALUES (1, 'When explaining something complicated, [Target] uses easy to understand language');
INSERT INTO `Slackbot_DB`.`questions` (`question_id`, `question`) VALUES (2, '[Target] distributes work to others well');
INSERT INTO `Slackbot_DB`.`questions` (`question_id`, `question`) VALUES (3, '[Target] always turns in work on time');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Slackbot_DB`.`raters`
-- -----------------------------------------------------
START TRANSACTION;
USE `Slackbot_DB`;
INSERT INTO `Slackbot_DB`.`raters` (`rater_id`, `rater`) VALUES (1, 'jeff');
INSERT INTO `Slackbot_DB`.`raters` (`rater_id`, `rater`) VALUES (2, 'kevin');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Slackbot_DB`.`ask_table`
-- -----------------------------------------------------
START TRANSACTION;
USE `Slackbot_DB`;
INSERT INTO `Slackbot_DB`.`ask_table` (`job_id`, `target`, `question_id`, `rater_id`, `response`) VALUES (1, 'Jeff', 1, 1, NULL);
INSERT INTO `Slackbot_DB`.`ask_table` (`job_id`, `target`, `question_id`, `rater_id`, `response`) VALUES (3, 'Jeff', 2, 1, NULL);
INSERT INTO `Slackbot_DB`.`ask_table` (`job_id`, `target`, `question_id`, `rater_id`, `response`) VALUES (4, 'Alexander', 3, 1, NULL);
INSERT INTO `Slackbot_DB`.`ask_table` (`job_id`, `target`, `question_id`, `rater_id`, `response`) VALUES (2, 'Kevin', 2, 1, 'Y');

COMMIT;

